version: '3.8'

services:
  mysql:
    image: mysql:8.0-oracle
    container_name: mysql
    command: --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    hostname: mysql
    restart: always
    cap_add:
      - SYS_NICE
    env_file:
      - ./.env
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    volumes:
      - data:/var/lib/mysql

  mysql-init:
    image: mysql:8.0-oracle
    container_name: mysql-init
    hostname: mysql-init
    volumes:
      - ./db/init.sql:/tmp/init.sql
    env_file:
      - ./.env
    entrypoint: ["bash", "-c", "sleep 30 && mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --host=mysql --port=3306 < /tmp/init.sql && exit"]
    depends_on:
      - mysql

  cageofbackend:
    image: fabianoflorentino/cageofbackend:0.0.1
    container_name: cageofbackend
    hostname: cageofbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    depends_on:
      - mysql
      - mysql-init
    ports:
      - ${RAILS_LOCAL_PORT}:3000
    volumes:
      - .:/app
    links:
      - mysql
    tty: true
    stdin_open: true

volumes:
  data:
    driver: local
