---
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.try(:fetch, 'MYSQL_USER') %>
  password: <%= ENV.try(:fetch, 'MYSQL_PASSWORD') %>
  host: <%= ENV.try(:fetch, 'MYSQL_HOST') { 'localhost' } %>
  port: <%= ENV.try(:fetch, 'MYSQL_PORT') { '3306' } %>

development:
  <<: *default
  database: <%= ENV.try(:fetch, 'MYSQL_DATABASE')%>_development

test:
  <<: *default
  database: <%= ENV.try(:fetch, 'MYSQL_DATABASE')%>_test

production:
  <<: *default
  database: <%= ENV.try(:fetch, 'MYSQL_DATABASE') %>
